### ISSUE TITLE
Allfiles missing

### ISSUE THREAD

**Issue by bckelly** [MicrosoftLearning/DA-100KO-Analyzing-Data-with-Power-BI#1]
there do not seem to be any Allfiles in this course. @VlastimilKroupa Can you please reuse the Allfiles from the English? And please check/fix for the other languages, too.
This is the same as bug 34133 in AzDO. Ideally, we would link to the English Allfiles repo. Is this possible?

**Comment by LuongNguyen0906** [comment]
> there do not seem to be any Allfiles in this course. @VlastimilKroupa Can you please reuse the Allfiles from the English? And please check/fix for the other languages, too.
> This is the same as bug 34133 in AzDO. Ideally, we would link to the English Allfiles repo. Is this possible?

This issue was fixed for all languages.
